import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import Fastify from 'fastify';
import { z } from 'zod';
import { createAgentApp, defineAgent, tool } from '@swiftagent/sdk';
import { ENV_KEYS } from '@swiftagent/shared';

/**
 * __PROJECT_NAME__ backend — generated by create-swift-agent.
 *
 * Defines one agent with one Zod-schema tool, starts the SDK tool runner via
 * `app.listen()` (which also registers the agent with the control plane), and
 * exposes `GET /api/session` for the frontend. The workspace API key stays
 * server-side; the browser only ever sees a short-lived client token.
 */

/**
 * The demo tool. Its name (`local_echo`) matches the tool the local
 * `fixture/tool-call` model deterministically calls, so the docker compose
 * stack completes a real tool round trip with no provider key. Rename it once
 * you switch to a real model.
 */
export const echoTool = tool({
  name: 'local_echo',
  description: 'Echo a message back, optionally shouting it.',
  inputSchema: z.object({
    message: z.string().min(1),
    shout: z.boolean().optional(),
  }),
  execute: async ({ message, shout }, ctx) => {
    const text = shout ? message.toUpperCase() : message;
    return { echoed: text, sessionId: ctx.sessionId };
  },
});

/** Load the project-root .env when present (host runs). Existing env wins. */
function loadDotEnv(): void {
  try {
    process.loadEnvFile(fileURLToPath(new URL('../../.env', import.meta.url)));
  } catch {
    // No .env — fine: docker compose provides the environment directly.
  }
}

/** Read a value from `NAME`, falling back to the file named by `NAME_FILE`-style env. */
function envOrFile(name: string, fileEnvName: string): string | undefined {
  const direct = process.env[name];
  if (direct) return direct;
  const file = process.env[fileEnvName];
  if (!file) return undefined;
  try {
    return readFileSync(file, 'utf8').trim() || undefined;
  } catch {
    return undefined;
  }
}

/** Runner workspace id: env, else the bootstrap's runner-env.json handoff. */
function resolveRunnerWorkspaceId(): string | undefined {
  const direct = process.env[ENV_KEYS.RUNNER_WORKSPACE_ID];
  if (direct) return direct;
  const file = process.env.RUNNER_ENV_FILE;
  if (!file) return undefined;
  try {
    const parsed: unknown = JSON.parse(readFileSync(file, 'utf8'));
    const workspaceId = (parsed as { workspaceId?: unknown }).workspaceId;
    return typeof workspaceId === 'string' ? workspaceId : undefined;
  } catch {
    return undefined;
  }
}

async function main(): Promise<void> {
  loadDotEnv();

  const apiKey = envOrFile('SWIFT_AGENT_API_KEY', 'SWIFT_AGENT_API_KEY_FILE');
  if (!apiKey) {
    console.error(
      '[__PROJECT_NAME__] Missing SWIFT_AGENT_API_KEY (or a readable SWIFT_AGENT_API_KEY_FILE). ' +
        'Run `docker compose up -d` first — the bootstrap mints a dev key into ./.swiftagent-local/.',
    );
    process.exit(1);
  }

  const runnerWorkspaceId = resolveRunnerWorkspaceId();
  if (!runnerWorkspaceId || !process.env[ENV_KEYS.RUNNER_TOKEN_PUBLIC_KEY]) {
    console.warn(
      `[__PROJECT_NAME__] Set ${ENV_KEYS.RUNNER_TOKEN_PUBLIC_KEY} and ${ENV_KEYS.RUNNER_WORKSPACE_ID} ` +
        '(or RUNNER_ENV_FILE — see .env.example): app.listen() requires them.',
    );
  }

  const app = createAgentApp({
    apiKey,
    baseUrl: process.env.SWIFT_AGENT_BASE_URL,
    runnerWorkspaceId,
  });

  // `SWIFT_AGENT_MODEL` (set by the compose stack to the zero-key fixture
  // model) overrides the scaffolded default. Env is read here, at run time —
  // never at import time.
  app.agent(
    defineAgent({
      name: '__PROJECT_NAME__',
      model: process.env.SWIFT_AGENT_MODEL ?? '__DEFAULT_MODEL__',
      system:
        'You are a helpful assistant. Use the local_echo tool when asked to repeat something.',
      tools: [echoTool],
    }),
  );

  const server = Fastify({ logger: true });

  // Permissive CORS so the page works even without the Vite proxy; the
  // workspace API key never leaves this process.
  server.addHook('onRequest', async (_request, reply) => {
    reply.header('access-control-allow-origin', '*');
    reply.header('access-control-allow-methods', 'GET,OPTIONS');
    reply.header('access-control-allow-headers', 'content-type');
  });
  server.options('/api/session', async (_request, reply) => {
    reply.code(204).send();
  });

  // Mint a session for the browser: short-lived client token + the canonical
  // websocketUrl (threaded verbatim by the frontend).
  server.get('/api/session', async () => {
    const session = await app.sessions.create({
      agentName: '__PROJECT_NAME__',
      userId: 'local-user',
    });
    return {
      sessionId: session.sessionId,
      token: session.clientToken,
      websocketUrl: session.websocketUrl,
    };
  });

  // Starts the tool runner (hosting local_echo) and registers the agent with
  // the control plane. RUNNER_PORT is dedicated to the runner so it never
  // collides with the session route's PORT.
  const runnerPort = Number.parseInt(process.env.RUNNER_PORT ?? '8787', 10);
  await app.listen(runnerPort);

  const port = Number.parseInt(process.env.PORT ?? '4000', 10);
  await server.listen({ port, host: '0.0.0.0' });
  console.log(`[__PROJECT_NAME__] Session route listening on http://127.0.0.1:${port}/api/session`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
